accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),
]

bcre/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('', include('pages.urls', namespace='pages')),
    path('listings/', include('listings.urls', namespace='listings')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('admin/', admin.site.urls),

] + debug_toolbar_urls() + static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'
urlpatterns = [
    path('contact', views.contact, name='contact'),
    path('contact/delete/<int:contact_id>', views.delete_contact, name='delete_contact'),
     path('contact/edit/<int:contact_id>', views.edit_contact, name='edit_contact'),
]

listings/urls.py
from django.urls import path

from . import views

app_name = 'listings'
urlpatterns = [
    path('', views.index, name = 'listings'),
    path('<int:listing_id>', views.listing, name='listing'),
    path('search', views.search, name='search'),

]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib import messages, auth
from django.contrib.auth.models import User
from contacts.models import Contact


# Create your views here.

def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.error(request, "Username already exists !")
                return redirect("accounts:register")
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request, "Email already exists !")
                    return redirect("accounts:register")
                else:
                    user = User.objects.create_user(username=username, password=password, email=email, first_name=first_name, last_name=last_name)
                    user.save()
                    messages.success(request, "Account created successfully !")
                    return redirect("accounts:login")
        else:
            messages.error(request, "Passwords do not match !")
            return redirect("accounts:register")
    else:
        return render(request, 'accounts/register.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            messages.success(request, "You are now logged in !")
            return redirect("accounts:dashboard")
        else:
            messages.error(request, "Invalid credentials !")
            return redirect("accounts:login")
    else:
        return render(request,'accounts/login.html')

def logout(request):
    if request.method == "POST":
        auth.logout(request)
    return redirect("pages:index")

def dashboard(request):
    user_contacts = Contact.objects.order_by('-contact').filter(user_id=request.user.id)
    context = {"contacts" : user_contacts}

    return render(request,'accounts/dashboard.html', context)

templates/accounts/dashboard.html
{% extends "base.html" %}
{% load humanize %}

{% block title %} | {{user.first_name}} {{user.last_name}} {% endblock title %}
{% block content %}

 <section id="showcase-inner" class="py-5 text-white">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-12">
            <h1 class="display-4">{% if user.username %}{{user.first_name | title}} {{user.last_name | title}}'s Dashboard
            {% else %} User Dashboard (enter by URL) {% endif %} </h1>
            <p class="lead">Manage your BC Real Estate account</p>
          </div>
        </div>
      </div>
    </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href={% url "pages:index" %}> <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active">Dashboard</li>
        </ol>
      </nav>
    </div>
  </section>
{% include "partials/_alert.html" %}
  <section id="dashboard" class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>Welcome {{user.first_name | title}}</h2>
{% if contacts %}
          <p>Here are the property listings that you have inquired about</p>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Property</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {% for contact in contacts %}
              <tr>
                <td>{{contact.id}}</td>
                <td>{{contact.listing}}</td>
                <td>
                  <a class="btn btn-light" href="{% url 'listings:listing' contact.listing_id %}">View Listing</a>
                  <button class="btn btn-danger" data-url="{% url 'contacts:delete_contact' contact.id %}"  data-toggle="modal" data-target="#deleteConfirmModal" data-id="{{ contact.id }}">Delete Listing</button>
                  <a href="{% url 'contacts:edit_contact' contact.id %}" class="btn btn-success">edit message</a>
                </td>
              </tr>  
               {% endfor %}
            </tbody>
          </table>
{% endif %}
        </div>
      </div>
    </div>
  </section>
  <!-- Modal  -->

  <div class="modal fade" id="deleteConfirmModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Confirm Delete</h5>
          <button type="button" class="close" data-dismiss="modal">
            <span>&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this listing?</p>
        
          <a id="confirmDeleteBtn" class="btn btn-danger" href=""> 
            Yes
          </a> 
          <button class="btn btn-info" data-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>
  
{% endblock content %}

templates/accounts/login.html
{% extends "base.html" %}
{% block content %}

<section id="login" class="bg-light py-5">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto">
            {% include "partials/_alert.html" %}
            <div class="card">
              <div class="card-header bg-primary text-white">
                <h4><i class="fas fa-sign-in-alt"></i> Login</h4>
              </div>
              <div class="card-body">
                <form action={% url "accounts:login" %} method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="username">Username</label>
                    <input
                    id="username"
                      type="text"
                      name="username"
                      class="form-control"
                      requiredß
                    />
                  </div>

                  <div class="form-group">
                    <label for="password">Password</label>
                    <input
                    id="password"
                      type="password"
                      name="password"
                      class="form-control"
                      required
                    />
                  </div>

                  <input
                    type="submit"
                    value="Login"
                    class="btn btn-secondary btn-block"
                  />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>




{% endblock content%}

templates/accounts/register.html
{% extends "base.html" %}
{% block content %}

<section id="register" class="bg-light py-5">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto">
            {% include 'partials/_alert.html' %}
            <div class="card">
              <div class="card-header bg-primary text-white">
                <h4><i class="fas fa-user-plus"></i> Register</h4>
              </div>
              <div class="card-body">
                <form action={% url "accounts:register" %} method= "POST">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input
                      id="first_name"
                      type="text"
                      name="first_name"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="last_name">Last Name</label>
                    <input
                      id="last_name"
                      type="text"
                      name="last_name"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="username">Username</label>
                    <input
                      id="username"
                      type="text"
                      name="username"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="email">Email</label>
                    <input
                      id="email"
                      type="email"
                      name="email"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="password">Password</label>
                    <input
                      id="password"
                      type="password"
                      name="password"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label for="password2">Confirm Password</label>
                    <input
                      id="password2"
                      type="password"
                      name="password2"
                      class="form-control"
                      required
                    />
                  </div>
                  <input
                    type="submit"
                    value="Register"
                    class="btn btn-secondary btn-block"
                  />
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock content %}