bcre/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('', include('pages.urls', namespace='pages')),
    path('listings/', include('listings.urls', namespace='listings')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('admin/', admin.site.urls),

] + debug_toolbar_urls() + static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'
urlpatterns = [
    path('contact', views.contact, name='contact'),
    path('contact/delete/<int:contact_id>', views.delete_contact, name='delete_contact'),
     path('contact/edit/<int:contact_id>', views.edit_contact, name='edit_contact'),
]

listings/urls.py
from django.urls import path

from . import views

app_name = 'listings'
urlpatterns = [
    path('', views.index, name = 'listings'),
    path('<int:listing_id>', views.listing, name='listing'),
    path('search', views.search, name='search'),

]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

listings/models.py
from django.db import models

from django.utils import timezone
from realtors.models import Realtor
from datetime import datetime
from listings.choices import district_choices




# Create your models here.


class Listing(models.Model):
    realtor = models.ForeignKey(Realtor, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    price = models.IntegerField()
    address = models.CharField(max_length=200)
    street = models.CharField(max_length=200)
    district = models.CharField(max_length=50, choices=district_choices.items())
    description = models.TextField(blank=True)
    bedrooms = models.IntegerField()
    bathrooms = models.DecimalField(max_digits=2, decimal_places=1)
    clubhouse = models.IntegerField()
    sqrt = models.IntegerField()
    estate_size = models.FloatField(default=0.0)
    is_publish = models.BooleanField(default=True)
    list_date = models.DateTimeField(auto_now_add=True)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_5 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_6 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)


    class Meta:
        ordering = ('-list_date',)
        indexes = [models.Index(fields=['list_date'])]
    
    def __str__(self):
        return self.title
    

listings/views.py
from django.shortcuts import render, get_object_or_404
from listings.models import Listing
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from listings.choices import price_choices, bedroom_choices, district_choices





# Create your views here.


def index(request):
    listings = Listing.objects.all()
    paginator = Paginator(listings, 3)
    page = request.GET.get('page')
    paged_listings = paginator.get_page(page)
    context = {"listings" : paged_listings}

    return render(request,'listings/listings.html', context)

def listing(request,listing_id):
    listing = get_object_or_404(Listing,pk=listing_id)
    context = {"listing" : listing}
    return render(request, 'listings/listing.html', context)

def search(request):

    queryset_list = Listing.objects.order_by('-list_date')

    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(description__icontains=keywords)

    if 'title' in request.GET:
        title = request.GET['title']
        if title:
            queryset_list = queryset_list.filter(title__icontains=title)

    if 'district' in request.GET:
        district = request.GET['district']
        if district_choices:
            queryset_list = queryset_list.filter(district__iexact=district)

    if 'bedrooms' in request.GET:
        bedrooms = request.GET['bedrooms']
        if bedrooms:
            queryset_list = queryset_list.filter(bedrooms__lte=bedrooms)

    if 'price' in request.GET:
        price = request.GET['price']
        if price:
            queryset_list = queryset_list.filter(price__lte=price)
   



    context = {"price_choices" : price_choices,
               "bedroom_choices" : bedroom_choices,
               "district_choices" : district_choices,
               "listings" : queryset_list,
               "values" : request.GET}
    return render(request, 'listings/search.html', context)

templates/listings/listing.html
{% extends "base.html" %} 
<!-- load static -->
{% load static %}
{% load humanize %}
{% block title %} | {{listing.title | title}} {% endblock title %}
{% block content %} 

<section id="showcase-inner" class="py-5 text-white">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-12">
            <h1 class="display-4">{{listing.title | title}}</h1>
            <p class="lead"><i class="fas fa-map-marker"></i> {{listing.district | title}}</p>
          </div>
        </div>
      </div>
    </section>

    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
      <div class="container">
        <nav>
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href={% url "pages:index" %}>Home</a>
            </li>
            <li class="breadcrumb-item">
              <a href={% url "listings:listings" %}>Listings</a>
            </li>
            <li class="breadcrumb-item active">{{listing.title | title}}</li>
          </ol>
        </nav>
      </div>
    </section>

    {% include "partials/_alert.html" %}

    <!-- Listing -->

    <section id="listing" class="py-4">
      <div class="container">

         

        <a href={% url "listings:listings" %} class="btn btn-light mb-4">Back To Listings</a>
        <div class="row">
          <div class="col-md-9">


            <!-- Home Main Image -->

     

            <img
              src={{listing.photo_main.url}}
              alt=""
              class="img-main img-fluid mb-3"
            />
            <!-- Thumbnails -->
            <div class="row mb-5 thumbs">
              {% if listing.photo_1 %}
              <div class="col-md-2">
                <a
                  href={{listing.photo_1.url}}
                  data-lightbox="home-images"
                >
                  <img
                    src={{listing.photo_1.url}}
                    alt=""
                    class="img-fluid"
                  />
                </a>
              </div>
              {% endif %}
              
              {% if listing.photo_2 %}
              <div class="col-md-2">
                <a
                  href={{listing.photo_2.url}}
                  data-lightbox="home-images"
                >
                  <img
                    src={{listing.photo_2.url}}
                    alt=""
                    class="img-fluid"
                  />
                </a>
              </div>
              {% endif %}

              {% if listing.photo_3 %}
              <div class="col-md-2">
                <a
                  href={{listing.photo_3.url}}
                  data-lightbox="home-images"
                >
                  <img
                    src={{listing.photo_3.url}}
                    alt=""
                    class="img-fluid"
                  />
                </a>
              </div>
              {% endif %}

              {% if listing.photo_4 %}
              <div class="col-md-2">
                <a
                  href={{listing.photo_4.url}}
                  data-lightbox="home-images"
                >
                  <img
                    src={{listing.photo_4.url}}
                    alt=""
                    class="img-fluid"
                  />
                </a>
              </div>
              {% endif %}

              {% if listing.photo_5 %}
              <div class="col-md-2">
                <a
                  href={{listing.photo_5.url}}
                  data-lightbox="home-images"
                >
                  <img
                    src={{listing.photo_5.url}}
                    alt=""
                    class="img-fluid"
                  />
                </a>
              </div>
              {% endif %}

              {% if listing.photo_6 %}
              <div class="col-md-2">
                <a
                  href={{listing.photo_6.url}}
                  data-lightbox="home-images"
                >
                  <img
                    src={{listing.photo_6.url}}
                    alt=""
                    class="img-fluid"
                  />
                </a>
              </div>
              {% endif %}

            </div>
            
            <!-- Fields -->
            <div class="row mb-5 fields">
              <div class="col-md-6">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item text-secondary">
                    <i class="fas fa-money-bill-alt"></i> Asking Price:
                    <span class="float-right">${{listing.price | intcomma}}</span>
                  </li>
                  <li class="list-group-item text-secondary">
                    <i class="fas fa-bed"></i> Bedrooms:
                    <span class="float-right">{{listing.bedrooms}}</span>
                  </li>
                  <li class="list-group-item text-secondary">
                    <i class="fas fa-bath"></i> Bathrooms: 
                    <span class="float-right">{{listing.bathrooms}}</span>
                  </li>
                  <li class="list-group-item text-secondary">
                    <i class="fas fa-dumbbell"></i> ClubHouse: 
                    <span class="float-right">{{listing.clubhouse}}</span>
                  </li>
                </ul>
              </div>
              <div class="col-md-6">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item text-secondary">
                    <i class="fas fa-th-large"></i> Square Feet: 
                    <span class="float-right">{{listing.sqrt | intcomma}}</span>
                  </li>
                  <li class="list-group-item text-secondary">
                    <i class="fas fa-square"></i> Estate Size: 
                    <span class="float-right">{{listing.estate_size | intcomma}}</span>
                  </li>
                  <li class="list-group-item text-secondary">
                    <i class="fas fa-calendar"></i> Listing Date:
                    <span class="float-right">{{listing.list_date | timesince}}</span>
                  </li>
                  <li class="list-group-item text-secondary">
                    <i class="fas fa-bed"></i> Realtor:
                    <span class="float-right"> {{listing.realtor.name}} </span>
                  </li>
                </ul>
              </div>
            </div>

  

            <!-- Description -->
            <div class="row mb-5">
              <div class="col-md-12">
                {{listing.description | linebreaks}}
              </div>
            </div>
          </div>
          <div class="col-md-3">
            <div class="card mb-3">
              <img
                class="card-img-top"
                src={{listing.realtor.photo.url}}
                alt="Seller of the month"
              />
              <div class="card-body">
                <h5 class="card-title">Property Realtor</h5>
                <h6 class="text-secondary">{{listing.realtor.name | title}}</h6>
              </div>
            </div>
            <button
              class="btn-primary btn-block btn-lg"
              data-toggle="modal"
              data-target="#inquiryModal"
            >
              Make An Inquiry
            </button>
          </div>
        </div>
      </div>
    </section>

  

    <!-- Inquiry Modal -->
    <div class="modal fade" id="inquiryModal" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
            <button type="button" class="close" data-dismiss="modal">
              <span>&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form action="{% url 'contacts:contact' %}" method="POST">
              {% csrf_token %}
               <input type="hidden" name="listing_id" value="{{listing.id}}" />
                <input type="hidden" name="realtor_email" value="{{listing.realtor.email}}" />
                {% if user.is_authenticated %}
                <input type="hidden" name="user_id" value="{{user.id}}" />
                {% else %}
                <input type="hidden" name="user_id" value="0" />
                {% endif %}
              <div class="form-group">
                <label for="property_name" class="col-form-label"
                  >Property:</label
                >
                <input
                  type="text"
                  name="listing"
                  class="form-control"
                  value="{{listing.title | title}}"
                  readonly
                />
              </div>
              <div class="form-group">
                <label for="name" class="col-form-label">Name:</label>
                <input type="text" name="name" class="form-control" {% if user.is_authenticated %} value="{{user.first_name}} {{user.last_name}}" readonly {% endif %} />
              </div>
              <div class="form-group">
                <label for="email" class="col-form-label">Email:</label>
                <input type="email" name="email" class="form-control" {% if user.is_authenticated %} value="{{user.email}}" readonly {% endif %} />
              </div>
              <div class="form-group">ß
                <label for="phone" class="col-form-label">Phone:</label>
                <input type="text" name="phone" class="form-control" />
              </div>
              <div class="form-group">
                <label for="message" class="col-form-label">Message:</label>
                <textarea name="message" class="form-control"></textarea>
              </div>
              <hr />
              <input
                type="submit"
                value="Send"
                class="btn btn-block btn-secondary"
              />
            </form>
          </div>
        </div>
      </div>
    </div>


    <!-- Footer -->
    <footer id="main-footer" class="py-4 bg-primary text-white text-center">
      Copyright &copy;
      <span class="year"></span> BC Real Estate
    </footer>

{% endblock content %}

templates/listings/listings.html
{% extends "base.html" %} 
{% load humanize %}
{% block content %} 


 <section id="showcase-inner" class="py-5 text-white">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-12">
            <h1 class="display-4">Browse Our Properties</h1>
            <p class="lead">
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt,
              pariatur!
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
      <div class="container">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href={% url "pages:index" %}> <i class="fas fa-home"></i> Home</a>
            </li>
            <li class="breadcrumb-item active">Browse Listings</li>
          </ol>
        </nav>
      </div>
    </section>

   
    <!-- Listings -->
    <section id="listings" class="py-4">
      <div class="container">
        <div class="row">
          
          {% if listings %}
          {% for listing in listings %}

          <!-- Listing 1 -->
          <div class="col-md-6 col-lg-4 mb-4">
            <div class="card listing-preview">
              <img class="card-img-top" src={{listing.photo_main.url}} alt="" />
              <div class="card-img-overlay">
                <h2>
                  <span class="badge badge-secondary text-white">${{listing.price | intword}}</span>
                </h2>
              </div>
              <div class="card-body">
                <div class="listing-heading text-center">
                  <h4 class="text-primary">{{listing.title}}</h4>
                  <p>
                    <i class="fas fa-map-marker text-secondary"></i> {{listing.district}}
                  </p>
                </div>
                <hr />
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-th-large"></i> Sqft: {{listing.sqrt | intcomma}}
                  </div>
                  <div class="col-6">
                    <i class="fas fa-dumbbell"></i> clubhouse: {{listing.clubhouse}}
                  </div>
                </div>
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-bed"></i> Bedrooms: {{listing.bedrooms}}
                  </div>
                  <div class="col-6">
                    <i class="fas fa-bath"></i> Bathrooms: {{listing.bathrooms}}
                  </div>
                </div>
                <hr />
                <div class="row py-2 text-secondary">
                  <div class="col-12">
                    <i class="fas fa-user"></i> {{listing.realtor | title}}
                  </div>
                </div>
                <div class="row text-secondary pb-2">
                  <div class="col-6">
                    <i class="fas fa-clock"></i> {{listing.list_date | timesince}}
                  </div>
                </div>
                <hr />
                {% comment %} change link {% endcomment %}
                <a href={% url "listings:listing" listing.id %} class="btn btn-primary btn-block"
                  >More Info</a
                >
              </div>
            </div>
          </div>

          {% endfor %}
          {% else %}
          <div class="col-md-12">
            <h2>No listings available</h2>
          </div>
          {% endif %}
        </div>

  {% comment %} pagination {% endcomment %}
        <div class="row">
          <div class="col-md-12">
            {% if listings.has_other_pages %}
            <ul class="pagination">
              {% if listings.has_previous %}
              <li class="page-item">
                  <a class="page-link" href="?page={{listings.previouos_page_number}}" >&laquo;</a>
                <li>
              {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#">&laquo;</a>
              </li>
              {% endif %}
              {% for i in listings.paginator.page_range %}
              {% if listings.number == i %}
              <li class="page-item active">
                <a class="page-link">{{i}}</a>
              </li>
              {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{i}}">{{i}}</a>
              </li>
              {% endif %}
              {% endfor %}
              

              {% if listings.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{listings.next_page_number}}" >&raquo;</a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#">&raquo;</a>
              </li>
              {% endif %}
            </ul>
            {% endif %}
          </div>
        </div>
      </div>
    </section>

{% endblock content %}

templates/listings/search.html
{% extends "base.html" %} {% block content %} {% load humanize %}

<section id="showcase-inner" class="showcase-search text-white py-5">
      <div class="container">
        <div class="row text-center">
          <div class="col-md-12">
            <form action={% url 'listings:search' %}>
              <!-- Form Row 1 -->
              <div class="form-row">
                <div class="col-md-4 mb-3">
                  <label class="sr-only">Keywords</label>
                  <input
                    type="text"
                    name="keywords"
                    class="form-control"
                    placeholder="Keyword (Bathrooms, ClubHouse, etc)"
                    value="{{values.keywords}}"
                  />
                </div>

                <div class="col-md-4 mb-3">
                  <label class="sr-only">Title</label>
                  <input
                    type="text"
                    name="title"
                    class="form-control"
                    placeholder="Title"
                    value="{{values.title}}"
                  />
                </div>

                <div class="col-md-4 mb-3">
                  <label class="sr-only">District</label>
                  <select name="district" class="form-control">
                    <option {% if not values.district %} selected="true" {% endif %} value="" >
                      Districts (All)
                    </option>
                    {% for key, value in district_choices.items %}
                    <option value="{{key}}" {% if key == values.district %} selected="true" {% endif %}>{{value}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <!-- Form Row 2 -->
              <div class="form-row">
                <div class="col-md-6 mb-3">
                  <label class="sr-only">Bedrooms</label>
                  <select name="bedrooms" class="form-control">
                    <option {% if not values.bedrooms %} selected="true" {% endif %} value="" >
                      Bedrooms (Any)
                    </option>
                    {% for key, value in bedroom_choices.items %}
                    <option value="{{key}}" {% if key == values.bedrooms %} selected="true" {% endif %}>{{value}}</option>
                    {% endfor %}
                  </select>
                </div>
                <div class="col-md-6 mb-3">
                  <select name="price" class="form-control">
                    <option {% if not values.price %} selected="true" {% endif %} value="" >
                      Max Price (All)
                    </option>
                    {% for key, value in price_choices.items %}
                    <option value="{{key}}" {% if key == values.price %} selected="true" {% endif %}>{{value}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
              <button class="btn btn-secondary btn-block mt-4" type="submit">
                Submit form
              </button>
            </form>
          </div>
        </div>
      </div>
    </section>

    <!-- Breadcrumb -->
    <section id="bc" class="mt-3">
      <div class="container">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item">
              <a href={% url "pages:index" %}> <i class="fas fa-home"></i> Home</a>
            </li>
            <li class="breadcrumb-item">
              <a href={% url "listings:listings" %}>Browse Listings</a>
            </li>
            <li class="breadcrumb-item active">Search Results</li>
          </ol>
        </nav>
      </div>
    </section>

    <!-- Listings -->
    <section id="listings" class="py-4">
      <div class="container">
        <div class="row">

          
          <!-- Listing 1 -->

          {% if listings %}
          {% for listing in listings %}
          
          <div class="col-md-6 col-lg-4 mb-4">
            <div class="card listing-preview">
              <img
                class="card-img-top"
                src={{listing.photo_main.url}}
                alt=""
              />
              <div class="card-img-overlay">
                <h2>
                  <span class="badge badge-secondary text-white">${{listing.price | intword}}</span>
                </h2>
              </div>
              <div class="card-body">
                <div class="listing-heading text-center">
                  <h4 class="text-primary">{{listing.title | title}}</h4>
                  <p>
                    <i class="fas fa-map-marker text-secondary"></i> {{listing.district}}
                  </p>
                </div>
                <hr />
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-th-large"></i> Sqft: {{listing.sqrt | intcomma}}
                  </div>
                  <div class="col-6">
                    <i class="fas fa-car"></i> ClubHouse: {{listing.clubhouse}}
                  </div>
                </div>
                <div class="row py-2 text-secondary">
                  <div class="col-6">
                    <i class="fas fa-bed"></i> Bedrooms: {{listing.bedrooms}}
                  </div>
                  <div class="col-6">
                    <i class="fas fa-bath"></i> Bathrooms: {{listing.bathrooms}}
                  </div>
                </div>
                <hr />
                <div class="row py-2 text-secondary">
                  <div class="col-12">
                    <i class="fas fa-user"></i> {{listing.realtor.name | title}}
                  </div>
                </div>
                <div class="row text-secondary pb-2">
                  <div class="col-6">
                    <i class="fas fa-clock"></i> {{listing.list_date | timesince}}
                  </div>
                </div>
                <hr />
                <a href={% url "listings:listing" listing.id %} class="btn btn-primary btn-block"
                  >More Info</a
                >
              </div>
            </div>
          </div>

          {% endfor %}
          {% else %}
          <div class="col-md-12">
            <p>No Listings Found</p>
          </div>
          {% endif %}
          

        {% comment %} endif & endfor {% endcomment %}

        </div>
      </div>
    </section>

{% endblock content %}